runtime: nodejs
env: flex

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '20'

manual_scaling:
  instances: 1

includes:
  - env.yaml

beta_settings:
  cloud_sql_instances: coba-987:asia-southeast2:binar-stupen