runtime: nodejs
env: flex

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '20'

manual_scaling:
  instances: 1

beta_settings:
  cloud_sql_instances: binar999:asia-southeast2:binar-instance-sql

includes:
  - env.yaml