name: CD

on: 
  push: 
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-20.04
    environment: VPS

    steps:
      - uses: actions/checkout@v4

      - name: Deploy using ssh 
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.LAPTOP_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            export PATH=$PATH:/usr/local/bin:/home/selalugt/.nvm/versions/node/v20.15.0/bin
            cd ~/myApps/mpkmb.com
            git pull origin main
            git status
            npm install --only-prod
            pm2 restart mpkmb.com