name: CD

on: 
  push: 
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-22.04
    environment: GCP

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup nodejs and npm
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
        
      - name: install dependencies
        run: npm i --frozen-lockfile
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get Secrets from Google Secret Manager
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@v1
        with:
          secrets: |
            DATABASE_URL
            JWT_SECRET
            IMAGEKIT_PUBLIC_KEY
            IMAGEKIT_PRIVATE_KEY
            IMAGEKIT_URL_ENDPOINT

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ steps.secrets.outputs.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ steps.secrets.outputs.JWT_SECRET }}" >> .env
          echo "IMAGEKIT_PUBLIC_KEY=${{ steps.secrets.outputs.IMAGEKIT_PUBLIC_KEY }}" >> .env
          echo "IMAGEKIT_PRIVATE_KEY=${{ steps.secrets.outputs.IMAGEKIT_PRIVATE_KEY }}" >> .env
          echo "IMAGEKIT_URL_ENDPOINT=${{ steps.secrets.outputs.IMAGEKIT_URL_ENDPOINT }}" >> .env

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy --quiet